version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ttt
      POSTGRES_PASSWORD: ttt
      POSTGRES_DB: tictactoe
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ttt']
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 4000
      HOST: 0.0.0.0
      DATABASE_URL: postgresql://ttt:ttt@postgres:5432/tictactoe
      PRISMA_DB_PROVIDER: postgresql
      WS_JWT_SECRET: super-secret-change
      JWT_ISSUER: tic-tac-toe
      FRONTEND_ORIGIN: http://web
      PUBLIC_WS_URL: http://api:4000
      TURN_TIMEOUT_SECONDS: 10
    ports:
      - '4000:4000'
    command: ["sh", "-c", "pnpm --filter @tic-tac-toe/api prisma:deploy && node dist/index.js"]

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    depends_on:
      - api
    ports:
      - '5173:80'

volumes:
  postgres-data:
    driver: local
