name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Typecheck
        run: npm run typecheck
      - name: Lint
        run: npm run lint
      - name: Unit tests
        run: npm test
      - name: Build
        run: npm run build
      - name: Smoke run (short)
        run: API_BASE_URL=http://localhost:8080 WS_BASE_URL=ws://localhost:8080/ws OUT_DIR=./results node dist/index.js smoke || true
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: k6-results
          path: results

